name: Create New Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the new project'
        required: true

jobs:
  create-new-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create New Repository
      id: create_repo
      uses: actions/github-script@v6
      with:
        script: |
          const projectName = '${{ github.event.inputs.project_name }}';
          const response = await github.repos.createInOrg({
            org: 'javid1e',
            name: projectName,
            private: true,
            auto_init: true
          });
          core.setOutput('repository_url', response.data.clone_url);

    - name: Clone Template Repository
      run: |
        git clone --bare https://github.com/javid1e/full_django_nextjs_dockerize_template.git
        cd full_django_nextjs_dockerize_template.git
        git push --mirror https://github.com/javid1e/${{ github.event.inputs.project_name }}.git

    - name: Checkout New Repository
      run: |
        git clone https://github.com/javid1e/${{ github.event.inputs.project_name }}.git
        cd ${{ github.event.inputs.project_name }}

    - name: Setup Frontend Branch
      run: |
        git checkout -b frontend
        git submodule add -b main https://github.com/javid1e/full_frontend_nextjs_shadcn_template.git ${{ github.event.inputs.project_name }}_frontend
        git commit -am "Add frontend submodule"
        git push origin frontend

    - name: Setup Backend Branch
      run: |
        git checkout -b backend
        git submodule add -b main https://github.com/javid1e/full_backend_django_rest_template.git ${{ github.event.inputs.project_name }}_backend
        git commit -am "Add backend submodule"
        git push origin backend

    - name: Setup Dockerize Branch
      run: |
        git checkout -b dockerize
        git submodule add -b main https://github.com/javid1e/full_dockerize_django_nextjs_template.git ${{ github.event.inputs.project_name }}_dockerize
        git commit -am "Add dockerize submodule"
        git push origin dockerize
