name: Update Backend Submodule

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Sync Submodules
      run: |
        git submodule sync
        git submodule update --init --recursive --remote --merge

    - name: Commit and Push Changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Update backend submodule"
          git push origin backend
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET }}

    - name: Create Pull Request to Main
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.SECRET }}
        branch: backend
        base: main
        title: "Update backend submodule"
        body: "This PR updates the backend submodule with the latest changes."
